### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by nyatindopatrick** [nyatindopatrick/the-news-week-clone#1]
Please leave some comments and suggestions.

**Comment by dili021** [comment]
Nice work so far!
-make sure to add nowrap to the nav so the links stay in 1 line.
-the nav isn't flexin'
-you gave the navbar justify-content-center(ed)
-you have a solid h-scroll on the page at all sizes. Try making the container into container-fluid so the page stays 100% width always

Just some thoughts :)

**Comment by Kyle-Law** [comment]
It looks nice 👍  Few remarks from me:
- OPINIONS title could be more aligned
- The navbar responsiveness, one of the key problems of this project. Personally I used grid for that but there shall be a better solution.
- Give some margin/padding between opinion img and details
- SPONSORED INSIGHTS (Ads) are not required but since you've included it, take them into considerations when dealing with their alignments and responsiveness.
- try not to use 'margin' or `padding` property in your css, use bootstrap predefined sizing classes instead. 

Overall, your project looks clean and fresh. Bravo customizing every single news with its respective pictures. Also, the top left the weather stuff is cool. :)

**Comment by patriciachrysy** [comment]
Good job so far Patrick. I will just give you some few tips thaught:
- Do not use container-fluid on your main content, it will prevent you from getting all the space you want. Just keep mx-auto and fixed width for your main (you can define that width in your CSS file for instance)
That all for me. Keep it up :-)
