### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by nyatindopatrick** [nyatindopatrick/the-news-week-clone#3]
Please leave any comments and suggestions

**Comment by Kyle-Law** [comment]
Great Job @nyatindopatrick  for making latest news and more stories section into 2 columns on smaller screen size, here are a few issues that I've found:
- NavBar is not responsive across medium-large screen size. search input get squeezed. Their nav titles should be in 1 line as well instead of two. I cured this using CSS Grid but not sure how could I solve it using Flexbox. Hmm...
- On smaller screen size, the margin between opinion title and author is slightly too much. The problems occur because you make it as 2 different rows. 
![image](https://user-images.githubusercontent.com/55923773/74712677-d5c53d00-5261-11ea-9bb1-62130282d59f.png) Not sure if you could fix it without affecting the HTML code.

Overall it looks decent. Good job customizing every news and including sponsored articles. :)

**Comment by patriciachrysy** [comment]
Good job @nyatindopatrick, I can't give any remark because I think my responsive tool may be broken. Anyway, good job!

**Comment by dili021** [comment]
You really cloned it!
some minor details to think about: 

runaway search bar 
![image](https://user-images.githubusercontent.com/55356496/74712617-00de6b00-5227-11ea-8022-df9b0f0074e0.png)

the issue is covering "see all features" when it wraps
![image](https://user-images.githubusercontent.com/55356496/74712837-8f52ec80-5227-11ea-8db0-2fc25914ae58.png)

these are also wrapping
![image](https://user-images.githubusercontent.com/55356496/74712820-88c47500-5227-11ea-8d10-15ab67a18f36.png)

I think most of the elements would benefit from a bit more py and a bit less px when <768px
You want them to be full screen but not sitting on top of each other. The py is mostly related to the last 1/4 of the page.

Excellent work, this is me just prepping you for Maria :laughing:

**Comment by nyatindopatrick** [comment]
Thank you all for the comments.
